/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppEstudosRouteImport } from './routes/_app/estudos'
import { Route as AppProgressoRouteImport } from './routes/_app/progresso'
import { Route as AppTarefasRouteImport } from './routes/_app/tarefas'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppEstudosRoute = AppEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaRoute
  '/estudos': typeof AppEstudosRoute
  '/progresso': typeof AppProgressoRoute
  '/tarefas': typeof AppTarefasRoute
}
export interface FileRoutesByTo {
  '/agenda': typeof AppAgendaRoute
  '/estudos': typeof AppEstudosRoute
  '/progresso': typeof AppProgressoRoute
  '/tarefas': typeof AppTarefasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/estudos': typeof AppEstudosRoute
  '/_app/progresso': typeof AppProgressoRoute
  '/_app/tarefas': typeof AppTarefasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agenda' | '/estudos' | '/progresso' | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to: '/agenda' | '/estudos' | '/progresso' | '/tarefas' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/agenda'
    | '/_app/estudos'
    | '/_app/progresso'
    | '/_app/tarefas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estudos': {
      id: '/_app/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AppEstudosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progresso': {
      id: '/_app/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppEstudosRoute: typeof AppEstudosRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppEstudosRoute: AppEstudosRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
